model_name: "TemporalMaxerArchitecture"
dataset_name: i5O
devices: ['cuda:0']
train_split: ['validation']
val_split: ['test']
dataset: {
  json_file: /data/fady/aar/video_features/annotations/i5Oannotations_tsp_r21d_rgb.json,
  feat_folder: /data/i5O/i5OData_30fps/TSP_features/r2plus1d_34-tsp_on_thumos14_features/stride_1/,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20,
  input_dim: 512,
  feat_stride: 1,
  num_frames: 16,
  default_fps: 15,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  backbone_type: convPooler,
  backbone_arch: [2, 5], # [#feature projection layers, #downsampling layer]
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  assigner: {
    iou_weight: 2,
    cls_weight: 1.0,
    center_radius: 1.5,
    keep_percent: 1.0,
    confuse_weight: 0.0
  }
}
opt: {
  learning_rate: 0.0001,
  epochs: 60,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
  num_workers: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt

